//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashTicket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashDeskEntities : DbContext
    {
        public CashDeskEntities()
            : base("name=CashDeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Rey> Reys { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status_res> Status_res { get; set; }
        public virtual DbSet<Status_ticket> Status_ticket { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<Type_train> Type_train { get; set; }
        public virtual DbSet<Type_wagon> Type_wagon { get; set; }
        public virtual DbSet<Wagon> Wagons { get; set; }
    }
}
