//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wagon()
        {
            this.Places = new HashSet<Place>();
        }
    
        public int id_wagon { get; set; }
        public int train_id { get; set; }
        public int type_wagon_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Place> Places { get; set; }
        public virtual Train Train { get; set; }
        public virtual Type_wagon Type_wagon { get; set; }
    }
}
